font-family = "JetBrainsMono Nerd Font"
font-size = 12.0

background-opacity = 0.78
cursor-shape = "Underline"

palette = "tokyo-night"

hide-cursor-when-typing = true
scrollback-lines = 10000
bell = "none"
[terminal]
working-directory = "/home/armaghan/armaghan@work" 
